WITH RECURSIVE CTE AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE WHERE HOUR < 23
)

SELECT CTE.HOUR, IFNULL(COUNT, 0) COUNT
FROM CTE
    LEFT JOIN (
        SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
        FROM ANIMAL_OUTS
        GROUP BY HOUR(DATETIME)
    ) T
    ON CTE.HOUR = T.HOUR
ORDER BY HOUR;