SELECT MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE
    JOIN REST_REVIEW
    ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE MEMBER_PROFILE.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_PROFILE.MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) RANKING
        FROM MEMBER_PROFILE
            JOIN REST_REVIEW
            ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
    GROUP BY MEMBER_PROFILE.MEMBER_ID) T
    WHERE RANKING = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;