SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) T
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;