SELECT YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT USER_INFO_2021.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_INFO_2021.USER_ID) / (
         SELECT COUNT(*)
         FROM USER_INFO
         WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) USER_INFO_2021
    JOIN ONLINE_SALE
    ON USER_INFO_2021.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR(SALES_DATE),
    MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;