SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female') AND SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male');