SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, BOOK.CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM BOOK
    JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;