SELECT HISTORY_ID,
    ROUND((DATEDIFF(END_DATE, START_DATE) + 1) *
        CASE
            # 5%, 8% 15%
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 < 7 THEN 1
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 < 30 THEN 0.95
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 < 90 THEN 0.92
            ELSE 0.85
        END * DAILY_FEE, 0) FEE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭') T
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ON T.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
ORDER BY FEE DESC, HISTORY_ID;